asdf-vm/asdf-elixir

bin/list-all
Three days ago Elixir 1.2.5 was released. When I tried to install it using asdf it was not included in the list of available versions. In fact, the last version included was 1.2.3 (there is an open pull request in #7 to add Elixir 1.2.4 to the list).
Ignoring the fact that the version 1.2.5 was not included, I tried to install it using `asdf install elixir 1.2.5`, which worked flawlessly :+1: 
I decided to take a look at the code and saw that currently, the list of available versions is simply a hardcoded list. Therefore this list must be manually updated to include each Elixir version.
This pull request replaces the hardcoded list of available versions with a list of releases directly fetched from the GitHub API. It works a little bit slower because it has to make a HTTP request, but it …
=> Fetch available Elixir versions from GitHub API

bin/list-all
This PR fixes the list-all. RC versions are now correctly listed.
Fixes https://github.com/asdf-vm/asdf-elixir/issues/13
\\cc: @tuvistavie @Stratus3D
=> Fix #13: list all versions including rc versions

bin/list-all
As discussed in #13, I added an authorization token so the tests pass on Travis, as it seems a lot of OSX builds use the same IP.
=> Use Github authentication to list releases

README.md, bin/install
Previously we just installed the precompiled Elixir binaries
for the latest supported OTP version. However sometimes people
would need the binaries to have been compiled against a more
recent OTP release.
This patch lets you append '-otp-${OTP_VERSION}' to any installable
version to fix this issue.
Closes #27
=> Let users specify the otp version for precompiled binaries.

bin/list-all
Currently `asdf list-all elixir` displays only the last 30 versions. This is due to pagination in the GitHub API. This pull request aims to fix this behaviour by asking 100 items per page, which is the maximum accepted by the API.
This fix works for now, but as soon as we will reach the 101st release we’ll need to make multiple requests to GitHub.
=> Make list-all list up to 100 Elixir versions

bin/install
This PR improves upon the work @fkumro did in #2. Instead of downloading the entire file, we simply check the headers (I passed the `-I` option to `curl`).
Additionally, I've improved the error messages to make them correct.
Another issue related to this problem is #18, which we would be able to close when this get's merged.
=> Fix 404 download error messages

README.md
I've created a listing of all packages hex bob does keep. I've added it to the README so people don't have to guess what is available and what isn't.
=> Add status page for bobs precompiled packages

README.md
Thanks to @TheFirstAvenger and @bitwalker for explaining this to me
=> Expand instructions for using custom-compiled elixir

bin/list-all
Use [Bob the Builder's](https://github.com/hexpm/bob) list of available builds instead of [Elixir's GitHub tags](https://github.com/elixir-lang/elixir/tags). 
This list is published at https://repo.hex.pm/builds/elixir/builds.txt. @ericmj I assume this is ok to use?
There are some differences:
- anyone using 0.12.3 or earlier won't have their version show up anymore. But, using master now, running `asdf install elixir 0.7.2` doesn't work anyway.
- Bob the Builder builds a `major.minor` version as well as `major.minor.patch` which isn't helpful for asdf's use case to lock versions. I've stripped these from the output so they don't show up. I do this by removing any line that only has one `.` character.
- RC versions now show up.
- OTP versions now show up.
- master now shows up.
Here's the …
=> Use Bob the Builder's list of Elixir builds instead of GitHub tags

bin/install
Why:
* The conditional branch is using a negative comparison but it defines
both branches, breaking the consistency of these checks throughout the
install script.
Note: this is the first change in a series towards simplifying a bit the code in the install script, to improve robustness, readability, and debugging. Hope it's welcome :smile:
=> Invert inner installation conditional

bin/install
Why:
- The install script uses a recurrent logical branching around install type, which forces the multiple layers of functions to pass this value throughout the entire flow.
- The install script also has some redundant details in the messages shown to the user that can be simplified.
- From #78, when the connection to the releases server fails the error message redirects users to the Elixir repo on GitHub. However known versions are installed from hex.pm.
These changes address the issue by:
- Following up on #77, and addressing the full scope of #78, refactoring `bin/install` in four distinct steps, one in each commit for easier review.
These changes remove most of the logical branching around the install type and cleanup some of the associated code.
=> Simplify install script

bin/list-all
Why:
* This script relies on a builds file in https://hex.pm which lists the known builts available in their servers. However, if for some reason this download fails, the script simply outputs the message returned by the server. In particular, if the path for this file changes, since https://hex.pm is using AWS S3 underneath, the result of requesting a file that does not exist is not an error message, but an AWS S3 XML Access Denied response.
* The list-all script, while small, looks a bit complicated, and is currently performing some transformations that have no effect in the current content of the builds file. See https://gist.github.com/pfac/c83a6244275b0ba1abbdfeeb02f7f261 for further details.
This change addresses these issues by:
* Documenting the sorting function as-is, for better …
=> Simplify list-all script

bin/install
Sometimes invalid endpoints return status codes of 403. Both 404 and 403 should be considered not found in this case.
Fixes https://github.com/asdf-vm/asdf/issues/701
=> Correct version check when trying to download zip file

bin/install
By showing the actual HTTP status code we can have a little more insight into what exactly went wrong.
=> Improve install error message

bin/install
Even though the `install_elixir_ref` command works correctly, ir relies in an unexpected variable scoping behavior. In bash, local variables from the caller apparently leak to callees, even overrides are allowed.
https://stackoverflow.com/q/41770139/458304
=> Fix variable usage on install_elixir_ref

bin/exec-env, bin/install
After installing an Elixir version I'm always running into the fact that I have to add rebar and hex because it's a new version. Theoretically some of it can be shared across versions, but given some tickets I read that seems hard to track and might break. This however just automates a manual step that *most* users are now running manually. We can also hide it behind an ENV variable if that is preferable, but I don't think it harms the user in any way.
=> Add auto install of hex and rebar

bin/exec-env, bin/install
Reverts asdf-vm/asdf-elixir#89
For context: https://github.com/asdf-vm/asdf-elixir/issues/90
This revert doesn't attempt to fix the functionality introduced in asdf-vm/asdf-elixir#89, just roll it back to fix `asdf install` functionality until a proper fix is in place.
=> Revert "Add auto install of hex and rebar"

.travis.yml
TRAVIS_BRANCH points to target branch in PRs
From the [documentation](https://docs.travis-ci.com/user/environment-variables/)
> TRAVIS_BRANCH:
>  - for push builds, or builds not triggered by a pull request, this is the name of the branch.
>  - for builds triggered by a pull request this is the name of the branch targeted by the pull request.
=> Test plugin version as checked out by Travis

bin/install
Trying to normalize where source materials are stored across plugins.
=> Use $ASDF_DOWNLOAD_PATH if possible

bin/install
The `cp` command doesn't have a `-T` switch on Mac OS:
```
Build succeeded!
cp: illegal option -- T
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```
=> Fix cp error on Mac OS

bin/install
Provide a more actionable error message when unzip is not installed.
I lost half an hour until I realized what the error message 'ERROR: unzip not found' meant.
(I figured it out reading the source of this plugin.)
Only after that I found issue #53 and the accompanying PR.
=> Tweak error message in case unzip is not installed

README.md, bin/exec-env, bin/install
The problem was that the newly installed elixir wasn't in the path. This is because reshim happens after installation of elixir. There is no default post-install which could take place after the reshim.
I tested this on a fresh install and it worked.
@dobs would you be so kind to confirm if this fix is proper and working in your environment? Sorry for the trouble :)
=> Add auto install of hex and rebar including path of the freshly installed elixir

bin/install, bin/list-all
Also adds the curl flag `-L` to follow redirects. Since this was missing it unfortunately means that older versions of asdf-elixir we stop serving builds on repo.hex.pm and instead redirect to builds.hex.pm.
=> Use new domain repo.hex.pm => builds.hex.pm

README.md
The URL currently in the README links to a 404 on hexdocs. This updates that URL in the README.
=> Updates doc URL for compatibility between elixir and erlang

bin/exec-env
If you are using **asdf-direnv** with **asdf-elixir** and try to execute
the command `asdf direnv shell elixir $version -- echo "hi"` will raise
the error "unbound variable" because the `direnv` uses `set -u` by
default.
I got this error when I try to setup this hook on `~/.asdfrc` to always
install the `local.hex` and `local.rebar`:
```
post_asdf_install_elixir = asdf direnv shell elixir $version -- mix do local.hex --force, local.rebar --force
```
The hack was always use a empty string if the variable is not defined.
But is possible to add a `set +u` at the beginning of the file and `set -u`
at the end, but set `set -u` at the end can cause a unexpected side
effect for another script.
=> Avoid unbound variable error when nounset is enabled

README.md
Upcoming asdf release will not support the hyphenated `plugin-add`
ref
https://github.com/asdf-vm/asdf/blob/97c242eb38f49628486fd414743ff0e6539135da/docs/guide/upgrading-from-v0-15-to-v0-16.md?plain=1#L23
=> docs(install): replace plugin-add

bin/latest-stable
=> latest-stable script compatibility fixes
